### ISSUE TITLE
No Release for Angular 15

### ISSUE THREAD

**Issue by ichdertobi** [marco-martins/angular-line-awesome#24]
Would it be possible to get a release for Angular 15 or making version 16 compatible to angular 15?

**Comment by marco-martins** [comment]
Hi Tobias, I just released the version to Angular 15. Please check on npmjs. 😉 
Note that the version is not mentioned in the README file, but it is now available in the package.

https://www.npmjs.com/package/angular-line-awesome?activeTab=versions

**Comment by ichdertobi** [comment]
Thx for the fast response and work!
Works now with a angular 15 project
