### ISSUE TITLE
Importing the directory "./icons" is forbidden 

### ISSUE THREAD

**Issue by raygig** [marco-martins/angular-line-awesome#41]
With Angular 18.2.9 I am getting this error message when serving or building the app.

[ERROR] Could not resolve "angular-line-awesome/icons"

    apps/client/src/app/core/core.module.ts:59:285:
      59 │ ...Life, lasUser, lasUserCircle, } from 'angular-line-awesome/icons';
         ╵                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  Importing the directory "./icons" is forbidden by this package:

    node_modules/angular-line-awesome/package.json:19:15:
      19 │     "./icons": "./icons",
         ╵                ~~~~~~~~~

  The presence of "exports" here makes importing a directory forbidden:

    node_modules/angular-line-awesome/package.json:18:2:
      18 │   "exports": {
         ╵   ~~~~~~~~~

  You can mark the path "angular-line-awesome/icons" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.

=====================

I was able to resolve this issue by changing node_modules/angular-line-awesome/package.json

### From
  "exports": {
    "./icons": "./icons",

### To 
  "exports": {
    "./icons": "./icons/index.js",

We are trying to get a release out and this is holding us up. Is there anyway you can publish this in the next couple of days?

Thanks

**Comment by marco-martins** [comment]
Hi @raygig, thank you for the message.

I ran some tests on my end and encountered the same error. I'm not sure if this is related to the latest version of Node, but I'm surprised that nobody has noticed it yet.

Anyway, I've already implemented a fix, and it seems to be working properly now. Please install the latest version of the package (18.0.2).

Happy coding 😉

**Comment by raygig** [comment]
@marco-martins The fix worked! Thanks again!
